CLIENT-4299: Activate test step for RPMs

diff --git a/.github/workflows/something.yml b/.github/workflows/something.yml
--- a/.github/workflows/something.yml
+++ b/.github/workflows/something.yml
@@ -298,74 +298,74 @@ jobs:
           echo "I know this is the wrong package to install...need to find out the right one"
           sudo apt-get update && sudo apt-get install -y aerospike-client-c
 
-#  use-rpm-artifacts:
-#    runs-on: ubuntu-22.04
-#    if: github.actor != 'dependabot[bot]'
-#    container:
-#      image: rockylinux:9
-#    needs: [extract-version, artifacts-cicd]
-#    steps:
-#      - name: Harden the runner (Audit all outbound calls)
-#        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
-#        with:
-#          egress-policy: audit
-#      - name: Install JFrog CLI
-#        id: jf
-#        uses: step-security/setup-jfrog-cli@893a92f96c7727242adf0e603c77b1f2a22390e1 # v4.9.1
-#        env:
-#          JF_URL: https://artifact.aerospike.io
-#          JF_PROJECT: test
-#        with:
-#          oidc-provider-name: gh-dev-test
-#          oidc-audience: aerospike/testing
-#      - name: Set up RPM repository
-#        run: |
-#          JF_USERNAME=${{ steps.jf.outputs.oidc-user }}
-#          JF_TOKEN=${{ steps.jf.outputs.oidc-token }}
-#          if [ -f /etc/os-release ]; then
-#              . /etc/os-release
-#              case "$ID" in
-#                  rhel|centos|almalinux|rocky)
-#                      DIST="el${VERSION_ID%%.*}"
-#                      ;;
-#                  amzn)
-#                      if [[ "$VERSION_ID" == "2023" ]]; then
-#                          DIST="amzn2023"
-#                      else
-#                          echo "Unsupported Amazon Linux version: $VERSION_ID"
-#                          exit 1
-#                      fi
-#                      ;;
-#                  *)
-#                      echo "Unsupported distro: $ID"
-#                      exit 1
-#                      ;;
-#              esac
-#          else
-#              echo "Cannot determine OS version"
-#              exit 1
-#          fi
-#
-#          ARCH=$(uname -m)
-#          REPO_FILE="/etc/yum.repos.d/aerospike-${DIST,,}-all.repo"
-#
-#          tee "$REPO_FILE" > /dev/null <<EOF
-#          [aerospike-${DIST,,}-test]
-#          name=Aerospike RPM Repo DEV for ${DIST^^} (\$basearch)
-#          baseurl=https://artifact.aerospike.io/artifactory/test-rpm-dev-local/${DIST,,}/$ARCH/
-#          username=${JF_USERNAME}
-#          password=${JF_TOKEN}
-#          enabled=1
-#          gpgcheck=1
-#          gpgkey=https://artifact.aerospike.io/artifactory/api/security/keypair/aerospike/public
-#          EOF
-#          echo "--------------------------------"
-#          cat "$REPO_FILE"
-#          echo "--------------------------------"
-#          echo "Aerospike .repo file written to $REPO_FILE"
-#      - name: Install RPMs
-#        run: |
-#          yum install hi -y
-#          echo "the test binary says:"
-#          hi
-#
+  use-rpm-artifacts:
+    runs-on: ubuntu-22.04
+    if: github.actor != 'dependabot[bot]'
+    container:
+      image: rockylinux:9
+    needs: [extract-version, artifacts-cicd]
+    steps:
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
+        with:
+          egress-policy: audit
+      - name: Install JFrog CLI
+        id: jf
+        uses: step-security/setup-jfrog-cli@893a92f96c7727242adf0e603c77b1f2a22390e1 # v4.9.1
+        env:
+          JF_URL: https://artifact.aerospike.io
+          JF_PROJECT: test
+        with:
+          oidc-provider-name: gh-dev-test
+          oidc-audience: aerospike/testing
+      - name: Set up RPM repository
+        run: |
+          JF_USERNAME=${{ steps.jf.outputs.oidc-user }}
+          JF_TOKEN=${{ steps.jf.outputs.oidc-token }}
+          if [ -f /etc/os-release ]; then
+              . /etc/os-release
+              case "$ID" in
+                  rhel|centos|almalinux|rocky)
+                      DIST="el${VERSION_ID%%.*}"
+                      ;;
+                  amzn)
+                      if [[ "$VERSION_ID" == "2023" ]]; then
+                          DIST="amzn2023"
+                      else
+                          echo "Unsupported Amazon Linux version: $VERSION_ID"
+                          exit 1
+                      fi
+                      ;;
+                  *)
+                      echo "Unsupported distro: $ID"
+                      exit 1
+                      ;;
+              esac
+          else
+              echo "Cannot determine OS version"
+              exit 1
+          fi
+
+          ARCH=$(uname -m)
+          REPO_FILE="/etc/yum.repos.d/aerospike-${DIST,,}-all.repo"
+
+          tee "$REPO_FILE" > /dev/null <<EOF
+          [aerospike-${DIST,,}-test]
+          name=Aerospike RPM Repo DEV for ${DIST^^} (\$basearch)
+          baseurl=https://artifact.aerospike.io/artifactory/test-rpm-dev-local/${DIST,,}/$ARCH/
+          username=${JF_USERNAME}
+          password=${JF_TOKEN}
+          enabled=1
+          gpgcheck=1
+          gpgkey=https://artifact.aerospike.io/artifactory/api/security/keypair/aerospike/public
+          EOF
+          echo "--------------------------------"
+          cat "$REPO_FILE"
+          echo "--------------------------------"
+          echo "Aerospike .repo file written to $REPO_FILE"
+      - name: Install RPMs
+        run: |
+          yum install hi -y
+          echo "the test binary says:"
+          hi
+
